[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
linker = "riscv64-unknown-elf-gcc"
runner = """\
qemu-system-riscv64 \
-machine virt \
-m 128M \
-cpu rv64 \
-smp 4 \
-echr 2 \
-nographic \
-serial mon:stdio \
-bios none \
-drive if=none,format=raw,file=hdd.dsk,id=primary \
-device virtio-blk-device,drive=primary \
-kernel"""
