[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
  '-C', 'link-arg=-Tvirt.ld',
]
runner = """\
qemu-system-riscv64 \
-machine virt \
-m 128M \
-cpu rv64 \
-smp 4 \
-echr 2 \
-nographic \
-serial mon:stdio \
-bios none \
-kernel"""
